SELECT TITLE , board.BOARD_ID , REPLY_ID , reply.WRITER_ID , reply.CONTENTS , DATE_FORMAT(reply.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE 
FROM USED_GOODS_BOARD board
INNER JOIN USED_GOODS_REPLY reply on board.BOARD_ID = reply.BOARD_ID
WHERE DATE_FORMAT(board.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY CREATED_DATE , TITLE